apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-controller
  namespace: chat-me
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://chat-me-delta.vercel.app"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
    - host: chatme-server.safvancmc.in
      http:
        paths:
          # Chat service socket.io
          - path: /chat/socket.io
            pathType: Prefix
            backend:
              service:
                name: chat-me-chat-service
                port:
                  number: 1239

          # Notification service socket.io
          - path: /notification/socket.io
            pathType: Prefix
            backend:
              service:
                name: chat-me-notification-service
                port:
                  number: 1236

          # Regular API routing (forward as-is)
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: chat-me-auth-service
                port:
                  number: 1234

          - path: /api/admin
            pathType: Prefix
            backend:
              service:
                name: chat-me-admin-service
                port:
                  number: 1235

          - path: /api/notification
            pathType: Prefix
            backend:
              service:
                name: chat-me-notification-service
                port:
                  number: 1236

          - path: /api/profile
            pathType: Prefix
            backend:
              service:
                name: chat-me-profile-service
                port:
                  number: 1237

          - path: /api/post
            pathType: Prefix
            backend:
              service:
                name: chat-me-post-service
                port:
                  number: 1238

          - path: /api/chat
            pathType: Prefix
            backend:
              service:
                name: chat-me-chat-service
                port:
                  number: 1239

          - path: /api/job
            pathType: Prefix
            backend:
              service:
                name: chat-me-job-service
                port:
                  number: 1240

  tls:
    - hosts:
        - chatme-server.safvancmc.in
      secretName: chatme-tls
