apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-me-auth-deployment
  labels:
    name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - image: safvancmc/chat-me-auth-service:latest
        name: auth-service
        envFrom:
          - configMapRef:
              name: auth-service-config