apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-me-chat-deployment
  labels:
    app: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
      - name: chat-service
        image: safvancmc/chat-me-chat-service:latest
        ports:
        - containerPort: 1239
        envFrom:
        - configMapRef:
            name: chat-service-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"