apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-me-notification-deployment
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: safvancmc/chat-me-notification-service:latest
        ports:
        - containerPort: 1236
        envFrom:
        - configMapRef:
            name: notification-service-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"