apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-me-profile-deployment
  labels:
    app: profile-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      containers:
      - name: profile-service
        image: safvancmc/chat-me-profile-service:latest
        ports:
        - containerPort: 1237
        envFrom:
        - configMapRef:
            name: profile-service-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"